### ISSUE TITLE
How do you deal with ACE2005

### ISSUE THREAD

**Issue by justhuan** [laituan245/eventcoref#2]
When I try to reproduce this work, it will say " No such file or directory: 'resources/ACE05-E/train.oneie.json'". Could you please provide me with the method of preprocessing ACE2005?

**Comment by laituan245** [comment]
The original ACE dataset is available here: https://catalog.ldc.upenn.edu/LDC2006T06 (you need a license). Please use the scripts in OneIE (http://blender.cs.illinois.edu/software/oneie/) to obtain the data files train.oneie.json, dev.oneie.json, and test.oneie.json.
