### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by justhuan** [laituan245/eventcoref#3]
Dear author, I am sorry to bother you again. I got the *.oneie.json file with your help, but there was a new problem when I reworked the work :"No such file or directory: 'resources/ ace05-e-preds /train.json'". Excuse me, what is this file? How to get it? Finally, I am sorry to disturb you again and hope to get your reply. Thank you！

**Comment by laituan245** [comment]
So the folder `ace05-e-preds` should contain files with predicted mentions. You can use OneIE (http://blender.cs.illinois.edu/software/oneie/) to generate these prediction files (the trained model is also in that link).
